# Generated by Django 3.0.5 on 2020-12-18 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201218_0730'),
        ('vans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='van',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.User', verbose_name='Created by'),
        ),
    ]
