# Generated by Django 3.0.5 on 2020-12-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vans', '0002_van_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='van',
            name='economic_number',
        ),
        migrations.AddField(
            model_name='van',
            name='eco_num_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Economic Number Consecutive'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='van',
            name='eco_num_prefix',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3')], default='A1', max_length=2, verbose_name='Economic Number Prefix'),
            preserve_default=False,
        ),
    ]
