# Generated by Django 3.0.5 on 2020-12-21 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vans', '0003_auto_20201219_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='van',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vans.Van', verbose_name='Van'),
        ),
    ]
